// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module applyConvolution_applyConvolution_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sum_2_1,
        sum_1_1,
        sum_0_1,
        sum_2_2_out,
        sum_2_2_out_ap_vld,
        sum_1_2_out,
        sum_1_2_out_ap_vld,
        sum_0_21_out,
        sum_0_21_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sum_2_1;
input  [31:0] sum_1_1;
input  [31:0] sum_0_1;
output  [31:0] sum_2_2_out;
output   sum_2_2_out_ap_vld;
output  [31:0] sum_1_2_out;
output   sum_1_2_out_ap_vld;
output  [31:0] sum_0_21_out;
output   sum_0_21_out_ap_vld;

reg ap_idle;
reg sum_2_2_out_ap_vld;
reg sum_1_2_out_ap_vld;
reg sum_0_21_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond1_fu_116_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [1:0] p_t_fu_38;
wire   [1:0] empty_fu_122_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_p_t_load;
wire   [1:0] p_t_load_load_fu_113_p1;
reg   [31:0] sum_0_21_fu_42;
reg   [31:0] sum_1_2_fu_46;
reg   [31:0] sum_2_2_fu_50;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_76;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 p_t_fu_38 = 2'd0;
#0 sum_0_21_fu_42 = 32'd0;
#0 sum_1_2_fu_46 = 32'd0;
#0 sum_2_2_fu_50 = 32'd0;
#0 ap_done_reg = 1'b0;
end

applyConvolution_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond1_fu_116_p2 == 1'd0)) begin
            p_t_fu_38 <= empty_fu_122_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_t_fu_38 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((p_t_load_load_fu_113_p1 == 2'd0) & (exitcond1_fu_116_p2 == 1'd0))) begin
            sum_0_21_fu_42 <= 32'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            sum_0_21_fu_42 <= sum_0_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((p_t_load_load_fu_113_p1 == 2'd1) & (exitcond1_fu_116_p2 == 1'd0))) begin
            sum_1_2_fu_46 <= 32'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            sum_1_2_fu_46 <= sum_1_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((1'b1 == ap_condition_76)) begin
            sum_2_2_fu_50 <= 32'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            sum_2_2_fu_50 <= sum_2_1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_116_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_p_t_load = 2'd0;
    end else begin
        ap_sig_allocacmp_p_t_load = p_t_fu_38;
    end
end

always @ (*) begin
    if (((exitcond1_fu_116_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_0_21_out_ap_vld = 1'b1;
    end else begin
        sum_0_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_116_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_1_2_out_ap_vld = 1'b1;
    end else begin
        sum_1_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_116_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_2_2_out_ap_vld = 1'b1;
    end else begin
        sum_2_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_condition_76 = (~(p_t_load_load_fu_113_p1 == 2'd1) & ~(p_t_load_load_fu_113_p1 == 2'd0) & (exitcond1_fu_116_p2 == 1'd0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_fu_122_p2 = (ap_sig_allocacmp_p_t_load + 2'd1);

assign exitcond1_fu_116_p2 = ((ap_sig_allocacmp_p_t_load == 2'd3) ? 1'b1 : 1'b0);

assign p_t_load_load_fu_113_p1 = ap_sig_allocacmp_p_t_load;

assign sum_0_21_out = sum_0_21_fu_42;

assign sum_1_2_out = sum_1_2_fu_46;

assign sum_2_2_out = sum_2_2_fu_50;

endmodule //applyConvolution_applyConvolution_Pipeline_1
